name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NPM
        run: npm install
      - name: Build web assets
        run: npm run web:build && npm run web:build:html
      - name: Run front end tests
        run: npm run test:deploy
        # TODO:
        # Start redis-server detached
        # Start postgres container, add sample data to postgres
        # Start up Node
        # Run through end-to-end tests
