name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install NPM
        run: npm install
      - name: Run tests
        run: npm run test
